name: Continuous Benchmarking

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened, edited, synchronize]
    
  workflow_dispatch:

jobs:
  benchmark_pr_branch:        
    name: Continuous Benchmarking PRs with Bencher
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      
      - name: Set Flags
        run: export USE_CUDA=0
  
      - name: Install Protobuf
        run: sudo apt install protobuf-compiler
        
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "PyTorch_requirements.txt"
          
      - name: Configure CMake
        # Configure CMake with benchmarking option on
        run: cmake -DNT_ENABLE_BENCHMARKING=ON -DCMAKE_PREFIX_PATH=`python3 -c 'import torch;print(torch.utils.cmake_prefix_path)'` -B ${{github.workspace}}/build

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build
        
      - name: Track PR Benchmarks with Bencher
        working-directory: ${{github.workspace}}/build
        run: |
          ls
          bencher run \
          --project nutens \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch '${{ github.head_ref }}' \
          --branch-start-point '${{ github.base_ref }}' \
          --branch-start-point-hash '${{ github.event.pull_request.base.sha }}' \
          --testbed ubuntu-latest \
          --adapter cpp_google \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "./benchmarks/benchmarks --benchmark_format=json --benchmark_repetitions=16 --benchmark_min_warmup_time=60" \
