name: Publish to PyPi
    
on: 
  push:
  workflow_dispatch:
    
jobs:
  pypi_distribution:
    
    permissions:
      contents: write
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    secrets: inherit
      
    strategy: 
      fail-fast: false
      matrix:
        include:
          #- build_type: cpu
          #  platform: ubuntu-latest
            
          - build_type: cuda
            platform: ubuntu-latest

    ## ./ At start of reusable workflow indicates to use the one in current repo i.e. the from the current branch
    uses: ./.github/workflows/pypi-distribution-reusable.yaml
    with:
      platform: ${{ matrix.platform }}
      build_type: ${{ matrix.build_type }}
      
