name: Generate Python Stubs

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'python/**'
      - 'python/*'

  workflow_dispatch:

jobs:
  cpp-linter:
    permissions: write-all
    runs-on: ubuntu-22.04

    steps:

      # Checks-out repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive
          sudo apt-get install -y libjs-mathjax
          sudo apt-get install -y doxygen
          sudo apt-get install -y graphviz
          sudo apt-get install -y protobuf-compiler

      # Need to install nuTens in order for sphinx autodoc to pick it up
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "PyTorch_requirements.txt"

      - name: Build and install nuTens
        run: pip install --verbose .[docs]

      # make stub files
      - name: Make stubs
        run: |
          # Need to set the library path so that torch can find itself (:
          export LD_LIBRARY_PATH=`python3 -c 'import os;import torch;print(os.path.abspath(torch.__file__)[:-11])'`/lib:$LD_LIBRARY_PATH
          pybind11-stubgen --enum-class-locations "scalar_type:nuTens.dtype" --enum-class-locations "device_type:nuTens.dtype" -o stubs nuTens
          mv stubs/nuTens/pyNuTens/*.pyi python/nuTens/

      # commit the stub files to the repository
      - uses: EndBug/add-and-commit@v10 # You can change this to use a specific version.
        with:
          add: 'python/nuTens/*.pyi'
          author_name: ewanwm
          author_email: e.w.miller@imperial.ac.uk
          message: 'Commit python stubs (from Github Action: "Generate Python Stubs")'
          push: true
